spring:
  application:
    name: til-board

  datasource:
    url: jdbc:mysql://localhost:3306/tilboard
    username: root
    password: til_board

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    # JPA가 날리는 쿼리 콘솔에서 확인

jwt:
  secret: ${JWT_SECRET}
  access-expiration: ${JWT_ACCESS_EXPIRATION}
  refresh-expiration: ${JWT_REFRESH_EXPIRATION}